package config

const (
	EnvPrefix = "PACKFINDERZ"

	AppEnvDev  = "dev"
	AppEnvProd = "prod"

	EnvAppEnv  = "PACKFINDERZ_APP_ENV"
	EnvPort    = "PACKFINDERZ_APP_PORT"
	EnvSvcKind = "PACKFINDERZ_SERVICE_KIND"

	EnvDBDSN                  = "PACKFINDERZ_DB_DSN"
	EnvDBHost                 = "PACKFINDERZ_DB_HOST"
	EnvDBPort                 = "PACKFINDERZ_DB_PORT"
	EnvDBUser                 = "PACKFINDERZ_DB_USER"
	EnvDBPassword             = "PACKFINDERZ_DB_PASSWORD"
	EnvDBName                 = "PACKFINDERZ_DB_NAME"
	EnvDBSSLMode              = "PACKFINDERZ_DB_SSLMODE"
	EnvDBDriver               = "PACKFINDERZ_DB_DRIVER"
	EnvDBMaxOpenConns         = "PACKFINDERZ_DB_MAX_OPEN_CONNS"
	EnvDBMaxIdleConns         = "PACKFINDERZ_DB_MAX_IDLE_CONNS"
	EnvDBConnMaxLifetime      = "PACKFINDERZ_DB_CONN_MAX_LIFETIME"
	EnvDBConnMaxIdleTime      = "PACKFINDERZ_DB_CONN_MAX_IDLE_TIME"
	EnvRedisURL               = "PACKFINDERZ_REDIS_URL"
	EnvRedisAddr              = "PACKFINDERZ_REDIS_ADDR"
	EnvRedisPass              = "PACKFINDERZ_REDIS_PASSWORD"
	EnvRedisDB                = "PACKFINDERZ_REDIS_DB"
	EnvRedisPoolSize          = "PACKFINDERZ_REDIS_POOL_SIZE"
	EnvRedisMinIdleConns      = "PACKFINDERZ_REDIS_MIN_IDLE_CONNS"
	EnvRedisDialTimeout       = "PACKFINDERZ_REDIS_DIAL_TIMEOUT"
	EnvRedisReadTimeout       = "PACKFINDERZ_REDIS_READ_TIMEOUT"
	EnvRedisWriteTimeout      = "PACKFINDERZ_REDIS_WRITE_TIMEOUT"
	EnvJWTSecret              = "PACKFINDERZ_JWT_SECRET"
	EnvJWTIssuer              = "PACKFINDERZ_JWT_ISSUER"
	EnvJWTExpMins             = "PACKFINDERZ_JWT_EXPIRATION_MINUTES"
	EnvRefreshTokenTTLMinutes = "PACKFINDERZ_REFRESH_TOKEN_TTL_MINUTES"
	EnvUseSQLite              = "PACKFINDERZ_USE_SQLITE"
	EnvAutoMigrate            = "PACKFINDERZ_AUTO_MIGRATE"
	EnvAVScan                 = "PACKFINDERZ_AV_SCAN"
	EnvGCSMode                = "PACKFINDERZ_GCS_ACCESS_MODE"
	EnvArgonMemoryKB          = "PACKFINDERZ_ARGON_MEMORY_KB"
	EnvArgonTime              = "PACKFINDERZ_ARGON_TIME"
	EnvArgonParallelism       = "PACKFINDERZ_ARGON_PARALLELISM"
	EnvArgonSaltLen           = "PACKFINDERZ_ARGON_SALT_LEN"
	EnvArgonKeyLen            = "PACKFINDERZ_ARGON_KEY_LEN"

	EnvOpenAIKey         = "PACKFINDERZ_OPENAI_API_KEY"
	EnvGoogleMapsKey     = "PACKFINDERZ_GOOGLE_MAPS_API_KEY"
	EnvGCPProjectID      = "PACKFINDERZ_GCP_PROJECT_ID"
	EnvGCPCredsJSON      = "PACKFINDERZ_GCP_CREDENTIALS_JSON"
	EnvGoogleCredsFile   = "PACKFINDERZ_GOOGLE_APPLICATION_CREDENTIALS"
	EnvGCSBucket         = "PACKFINDERZ_GCS_BUCKET_NAME"
	EnvGCSUploadExpiry   = "PACKFINDERZ_GCS_UPLOAD_URL_EXPIRY"
	EnvGCSDownloadExpiry = "PACKFINDERZ_GCS_DOWNLOAD_URL_EXPIRY"

	EnvMaxUploadMB          = "PACKFINDERZ_MAX_UPLOAD_MB"
	EnvMediaImageMaxWidth   = "PACKFINDERZ_MEDIA_IMAGE_MAX_WIDTH"
	EnvMediaImageMaxHeight  = "PACKFINDERZ_MEDIA_IMAGE_MAX_HEIGHT"
	EnvMediaImageQuality    = "PACKFINDERZ_MEDIA_IMAGE_QUALITY"
	EnvMediaVideoCRF        = "PACKFINDERZ_MEDIA_VIDEO_CRF"
	EnvMediaVideoPreset     = "PACKFINDERZ_MEDIA_VIDEO_PRESET"
	EnvMediaVideoMaxBitrate = "PACKFINDERZ_MEDIA_VIDEO_MAX_BITRATE"
	EnvMediaPDFQuality      = "PACKFINDERZ_MEDIA_PDF_QUALITY"
	EnvMediaPDFDPI          = "PACKFINDERZ_MEDIA_PDF_DPI"

	EnvPubSubMediaTopic   = "PACKFINDERZ_PUBSUB_MEDIA_TOPIC"
	EnvPubSubMediaSub     = "PACKFINDERZ_PUBSUB_MEDIA_SUBSCRIPTION"
	EnvPubSubOrdersTopic  = "PACKFINDERZ_PUBSUB_ORDERS_TOPIC"
	EnvPubSubOrdersSub    = "PACKFINDERZ_PUBSUB_ORDERS_SUBSCRIPTION"
	EnvPubSubBillingTopic = "PACKFINDERZ_PUBSUB_BILLING_TOPIC"
	EnvPubSubBillingSub   = "PACKFINDERZ_PUBSUB_BILLING_SUBSCRIPTION"

	EnvStripeAPIKey        = "PACKFINDERZ_STRIPE_API_KEY"
	EnvStripeWebhookSecret = "PACKFINDERZ_STRIPE_WEBHOOK_SECRET"

	EnvSendgridAPIKey = "PACKFINDERZ_SENDGRID_API_KEY"
	EnvSendgridSender = "PACKFINDERZ_SENDGRID_FROM_EMAIL"

	EnvCloudSQLInstance    = "PACKFINDERZ_CLOUD_SQL_INSTANCE"
	EnvCloudSQLProxyPort   = "PACKFINDERZ_CLOUD_SQL_PROXY_PORT"
	EnvCloudSQLProxyBinary = "PACKFINDERZ_CLOUD_SQL_PROXY_BINARY"
)

var (
	legacyDBEnvVars = []string{
		EnvDBHost,
		EnvDBUser,
		EnvDBName,
	}
)
